/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.java.oop;

/**
 *
 * @author alvin
 */
import assignment.java.oop.panelsFM.ApprovePO_Panel;
import javax.swing.JPanel;
import java.awt.GridBagLayout;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.BorderFactory;
import java.awt.Color;




public class Finance_Manager extends javax.swing.JFrame {

    /**
     * Creates new form Finance_Manager
     */
    public Finance_Manager() {
    initComponents();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnApprovePO = new javax.swing.JButton();
        BtnModifyPO = new javax.swing.JButton();
        BtnViewInventory = new javax.swing.JButton();
        BtnProcessPayments = new javax.swing.JButton();
        BtnGenerateFinancialReports = new javax.swing.JButton();
        BtnViewPRs_POs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Btnlgout = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        BtnApprovePO.setText("Approve PO");
        BtnApprovePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApprovePOActionPerformed(evt);
            }
        });

        BtnModifyPO.setText("Modify PO (quantity/supplier)");

        BtnViewInventory.setText("View Inventory Updates");

        BtnProcessPayments.setText("Process Payments ");

        BtnGenerateFinancialReports.setText("Generate Financial Reports ");

        BtnViewPRs_POs.setText("View PRs and POs");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Financial Manager ");

        Btnlgout.setText("Log Out");

        mainContentPanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnModifyPO)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnApprovePO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnProcessPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnGenerateFinancialReports, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(BtnViewPRs_POs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(Btnlgout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(BtnApprovePO)
                .addGap(44, 44, 44)
                .addComponent(BtnModifyPO)
                .addGap(54, 54, 54)
                .addComponent(BtnViewInventory)
                .addGap(55, 55, 55)
                .addComponent(BtnProcessPayments)
                .addGap(39, 39, 39)
                .addComponent(BtnGenerateFinancialReports)
                .addGap(52, 52, 52)
                .addComponent(BtnViewPRs_POs)
                .addGap(51, 51, 51)
                .addComponent(Btnlgout)
                .addGap(21, 21, 21))
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
 
    private void BtnApprovePOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApprovePOActionPerformed
        loadPanel(new ApprovePO_Panel());

    }//GEN-LAST:event_BtnApprovePOActionPerformed

    private void loadPanel(JPanel panel) {
    mainContentPanel.removeAll();
    mainContentPanel.setLayout(new GridBagLayout());

    JPanel wrapper = new JPanel();
    wrapper.setLayout(new BorderLayout());
    wrapper.setPreferredSize(new Dimension(500,350)); // adjust size
    wrapper.add(panel, BorderLayout.CENTER);
    wrapper.setOpaque(false); // Make wrapper transparent if needed
    wrapper.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 2));


    GridBagConstraints gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.CENTER; // Center it
    gbc.insets = new java.awt.Insets(50, 50, 50, 50); // add margins top, left, bottom, right

    mainContentPanel.add(wrapper, gbc);

    mainContentPanel.revalidate();
    mainContentPanel.repaint();
}



    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApprovePO;
    private javax.swing.JButton BtnGenerateFinancialReports;
    private javax.swing.JButton BtnModifyPO;
    private javax.swing.JButton BtnProcessPayments;
    private javax.swing.JButton BtnViewInventory;
    private javax.swing.JButton BtnViewPRs_POs;
    private javax.swing.JButton Btnlgout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContentPanel;
    // End of variables declaration//GEN-END:variables
}
